import type {
  AccessoryOptionDto,
  InteriorOptionDto,
  TrimOptionDto,
  VehicleColorDto,
  VehicleDto,
  WheelOptionDto,
} from '../../modules/vehicles/dto.js';

const color = (
  id: string,
  name: string,
  hex: string,
  finish: VehicleColorDto['finish'],
  price = 0,
): VehicleColorDto => ({ id, name, hex, finish, price });

const PALETTE = {
  ivory: color('ivory', 'Studio Ivory', '#EDE6D2', 'solid'),
  graphite: color('graphite', 'Graphite Grey', '#4A5057', 'metallic', 900),
  indigo: color('indigo', 'Aurora Indigo', '#1C1A8A', 'metallic', 1400),
  ember: color('ember', 'Ember Orange', '#E8551B', 'pearl', 1800),
  crimson: color('crimson', 'Deep Crimson', '#8D1418', 'metallic', 1400),
  midnight: color('midnight', 'Midnight Slate', '#1E272E', 'solid'),
  glacier: color('glacier', 'Glacier Teal', '#2FAFAA', 'pearl', 1800),
  cobalt: color('cobalt', 'Cobalt Blue', '#1F6FC2', 'metallic', 1200),
  sage: color('sage', 'Sage Mist', '#B6BF9A', 'matte', 2400),
  pearl: color('pearl', 'Pearl White', '#F4F4F0', 'pearl', 1100),
  silver: color('silver', 'Lunar Silver', '#B9BEC4', 'metallic', 900),
};

const WHEELS: WheelOptionDto[] = [
  { id: 'aero-19', name: 'Aero 19"', sizeInches: 19, style: 'aero', price: 0 },
  { id: 'sport-20', name: 'Sport 20"', sizeInches: 20, style: 'sport', price: 1600 },
  { id: 'forged-21', name: 'Forged 21"', sizeInches: 21, style: 'forged', price: 3200 },
  { id: 'classic-18', name: 'Classic 18"', sizeInches: 18, style: 'classic', price: 0 },
];

const INTERIORS: InteriorOptionDto[] = [
  { id: 'int-stone', name: 'Stone Fabric', accent: '#B9B2A2', material: 'fabric', price: 0 },
  { id: 'int-black', name: 'Onyx Vegan Leather', accent: '#23272B', material: 'vegan-leather', price: 1500 },
  { id: 'int-tan', name: 'Saddle Leather', accent: '#A46B3A', material: 'leather', price: 2400 },
  { id: 'int-slate', name: 'Slate Alcantara', accent: '#4B5866', material: 'alcantara', price: 2900 },
];

const TRIMS: TrimOptionDto[] = [
  { id: 'trim-ash', name: 'Open-pore Ash', description: 'Natural light wood inlays', price: 0 },
  { id: 'trim-carbon', name: 'Matte Carbon', description: 'Woven carbon fibre inlays', price: 1200 },
  { id: 'trim-alu', name: 'Brushed Aluminium', description: 'Cool-touch metal inlays', price: 600 },
];

const ACCESSORIES: AccessoryOptionDto[] = [
  { id: 'acc-tow', name: 'Tow Package', description: 'Retractable hitch and wiring', price: 1100 },
  { id: 'acc-roof', name: 'Roof Rail System', description: 'Low-drag aluminium rails', price: 480 },
  { id: 'acc-mats', name: 'All-weather Mats', description: 'Moulded floor protection', price: 220 },
  { id: 'acc-charger', name: 'Home Wall Charger', description: '11 kW smart charger', price: 650 },
  { id: 'acc-sound', name: 'Studio Sound', description: '16-speaker premium audio', price: 1900 },
];

const pick = <T extends { id: string }>(source: T[], ...ids: string[]) =>
  ids.map((id) => source.find((item) => item.id === id)).filter((item): item is T => Boolean(item));

export const CATEGORY_SEED = [
  { slug: 'electric', label: 'Electric', description: 'Zero-emission drivetrains', icon: 'charging', sortOrder: 1 },
  { slug: 'performance', label: 'Performance', description: 'Built for the driver', icon: 'speed', sortOrder: 2 },
  { slug: 'luxury', label: 'Luxury', description: 'First-class comfort', icon: 'sparkle', sortOrder: 3 },
  { slug: 'family', label: 'Family', description: 'Space, safety and range', icon: 'users', sortOrder: 4 },
  { slug: 'adventure', label: 'Adventure', description: 'Capability beyond the tarmac', icon: 'layers', sortOrder: 5 },
  { slug: 'compact', label: 'Compact', description: 'Efficient city companions', icon: 'cube', sortOrder: 6 },
];

export const VEHICLE_CATALOG: VehicleDto[] = [
  {
    id: 'aureon-x1',
    slug: 'aureon-x1',
    manufacturer: 'Aureon',
    model: 'X1',
    variant: 'Long Range AWD',
    year: 2026,
    tagline: 'Quiet power for long horizons.',
    description:
      'The Aureon X1 pairs a dual-motor electric drivetrain with a calm, spacious cabin. Its low centre of gravity and adaptive air suspension make long journeys feel effortless.',
    category: ['electric', 'luxury', 'family'],
    bodyType: 'sedan',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 536,
    torque: 780,
    topSpeed: 250,
    acceleration: 3.4,
    range: 610,
    mileage: null,
    seats: 5,
    price: 68900,
    currency: 'USD',
    rating: 4.8,
    isNew: true,
    isFeatured: true,
    colors: [PALETTE.indigo, PALETTE.ivory, PALETTE.graphite, PALETTE.pearl, PALETTE.glacier],
    wheels: pick(WHEELS, 'aero-19', 'sport-20', 'forged-21'),
    interiors: INTERIORS,
    trims: TRIMS,
    accessories: pick(ACCESSORIES, 'acc-charger', 'acc-mats', 'acc-sound'),
    variants: [
      { id: 'std', name: 'Standard Range', price: 58900, power: 402, range: 480, acceleration: 4.6 },
      { id: 'lr', name: 'Long Range AWD', price: 68900, power: 536, range: 610, acceleration: 3.4 },
      { id: 'perf', name: 'Performance', price: 82900, power: 690, range: 560, acceleration: 2.7 },
    ],
    dimensions: { lengthMm: 4970, widthMm: 1964, heightMm: 1445, wheelbaseMm: 2960, cargoLiters: 561, weightKg: 2120 },
    features: ['Adaptive air suspension', 'Panoramic glass roof', 'Heated & ventilated seats', 'Frameless doors', 'Powered frunk'],
    technology: ['800V architecture', '15-minute 10–80% charging', 'Over-the-air updates', 'Augmented head-up display'],
    safety: ['Adaptive cruise with lane centring', 'Emergency steering assist', '360° camera', 'Nine airbags'],
    model3d: null,
    silhouette: 'sedan',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'sedan', profile: 'executive-ev' },
  },
  {
    id: 'velora-gt',
    slug: 'velora-gt',
    manufacturer: 'Velora',
    model: 'GT',
    variant: 'Coupé V6 Twin-Turbo',
    year: 2025,
    tagline: 'Every road becomes a stage.',
    description:
      'A front-mid-engine grand tourer with a carbon-composite body. The Velora GT balances raw performance with an unhurried, luxurious character.',
    category: ['performance', 'luxury'],
    bodyType: 'coupe',
    fuelType: 'petrol',
    transmission: 'dual-clutch',
    power: 612,
    torque: 800,
    topSpeed: 318,
    acceleration: 3.1,
    range: 720,
    mileage: 9.8,
    seats: 2,
    price: 148500,
    currency: 'USD',
    rating: 4.9,
    isFeatured: true,
    colors: [PALETTE.crimson, PALETTE.midnight, PALETTE.silver, PALETTE.ember],
    wheels: pick(WHEELS, 'sport-20', 'forged-21'),
    interiors: pick(INTERIORS, 'int-black', 'int-tan', 'int-slate'),
    trims: pick(TRIMS, 'trim-carbon', 'trim-alu'),
    accessories: pick(ACCESSORIES, 'acc-sound', 'acc-mats'),
    variants: [
      { id: 'gt', name: 'GT', price: 148500, power: 612, range: 720, acceleration: 3.1 },
      { id: 'gts', name: 'GT S', price: 172000, power: 680, range: 690, acceleration: 2.8 },
    ],
    dimensions: { lengthMm: 4720, widthMm: 1940, heightMm: 1290, wheelbaseMm: 2735, cargoLiters: 290, weightKg: 1620 },
    features: ['Carbon-ceramic brakes', 'Active rear wing', 'Sport exhaust', 'Launch control', 'Track telemetry'],
    technology: ['Torque-vectoring rear axle', 'Adaptive dampers', 'Driver-focused cockpit', 'Wireless smartphone integration'],
    safety: ['Forward collision warning', 'Blind-spot monitoring', 'Rear cross-traffic alert', 'Six airbags'],
    model3d: null,
    silhouette: 'coupe',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'coupe', profile: 'gt' },
  },
  {
    id: 'nexen-e7',
    slug: 'nexen-e7',
    manufacturer: 'Nexen',
    model: 'E7',
    variant: 'Family Crossover',
    year: 2026,
    tagline: 'Room for everything that matters.',
    description:
      'Seven seats, a flat floor and a charging network partnership make the Nexen E7 the electric crossover for growing families.',
    category: ['electric', 'family', 'adventure'],
    bodyType: 'suv',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 402,
    torque: 640,
    topSpeed: 200,
    acceleration: 5.2,
    range: 540,
    mileage: null,
    seats: 7,
    price: 62400,
    currency: 'USD',
    rating: 4.7,
    isNew: true,
    isFeatured: true,
    colors: [PALETTE.sage, PALETTE.pearl, PALETTE.graphite, PALETTE.cobalt],
    wheels: pick(WHEELS, 'aero-19', 'sport-20'),
    interiors: pick(INTERIORS, 'int-stone', 'int-black', 'int-tan'),
    trims: pick(TRIMS, 'trim-ash', 'trim-alu'),
    accessories: ACCESSORIES,
    variants: [
      { id: 'rwd', name: 'Rear-wheel Drive', price: 55900, power: 300, range: 500, acceleration: 6.8 },
      { id: 'awd', name: 'Dual Motor AWD', price: 62400, power: 402, range: 540, acceleration: 5.2 },
    ],
    dimensions: { lengthMm: 5030, widthMm: 1990, heightMm: 1700, wheelbaseMm: 3050, cargoLiters: 980, weightKg: 2380 },
    features: ['Three-row seating', 'Sliding second row', 'Vehicle-to-load outlets', 'Hands-free tailgate', 'Roof rails'],
    technology: ['Bidirectional charging', 'Route planner with charging stops', 'Digital key sharing', 'Rear-seat entertainment'],
    safety: ['Child presence detection', 'Trailer stability assist', 'Highway pilot', 'Ten airbags'],
    model3d: null,
    silhouette: 'suv',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'suv', profile: 'family-ev' },
  },
  {
    id: 'kairo-s',
    slug: 'kairo-s',
    manufacturer: 'Kairo',
    model: 'S',
    variant: 'Urban Hatch',
    year: 2025,
    tagline: 'Small footprint, big personality.',
    description:
      'The Kairo S is a compact hatchback built for cities: tight turning circle, clever storage and a cheerful, tactile interior.',
    category: ['compact', 'family'],
    bodyType: 'hatchback',
    fuelType: 'hybrid',
    transmission: 'automatic',
    power: 148,
    torque: 240,
    topSpeed: 185,
    acceleration: 8.9,
    range: 820,
    mileage: 24.5,
    seats: 5,
    price: 26900,
    currency: 'USD',
    rating: 4.5,
    colors: [PALETTE.glacier, PALETTE.ivory, PALETTE.ember, PALETTE.midnight],
    wheels: pick(WHEELS, 'classic-18', 'aero-19'),
    interiors: pick(INTERIORS, 'int-stone', 'int-black'),
    trims: pick(TRIMS, 'trim-ash', 'trim-alu'),
    accessories: pick(ACCESSORIES, 'acc-mats', 'acc-roof'),
    variants: [
      { id: 'base', name: 'S', price: 26900, power: 148, range: 820, acceleration: 8.9 },
      { id: 'plus', name: 'S Plus', price: 30400, power: 168, range: 790, acceleration: 8.1 },
    ],
    dimensions: { lengthMm: 4180, widthMm: 1780, heightMm: 1460, wheelbaseMm: 2640, cargoLiters: 380, weightKg: 1340 },
    features: ['Two-tone roof', 'Adjustable boot floor', 'Wireless charging pad', 'Ambient lighting'],
    technology: ['Self-charging hybrid', 'Predictive energy management', '10" touchscreen', 'Voice assistant'],
    safety: ['Automatic emergency braking', 'Lane keep assist', 'Traffic sign recognition', 'Seven airbags'],
    model3d: null,
    silhouette: 'hatch',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'hatch', profile: 'urban' },
  },
  {
    id: 'orion-touring',
    slug: 'orion-touring',
    manufacturer: 'Orion',
    model: 'Touring',
    variant: 'Estate Hybrid',
    year: 2025,
    tagline: 'The long way, comfortably.',
    description:
      'An elegant estate with a plug-in hybrid drivetrain. Orion Touring is built for people who travel far and carry a lot.',
    category: ['family', 'luxury'],
    bodyType: 'wagon',
    fuelType: 'hybrid',
    transmission: 'automatic',
    power: 340,
    torque: 520,
    topSpeed: 240,
    acceleration: 5.6,
    range: 980,
    mileage: 19.2,
    seats: 5,
    price: 57800,
    currency: 'USD',
    rating: 4.6,
    colors: [PALETTE.graphite, PALETTE.ivory, PALETTE.cobalt, PALETTE.sage],
    wheels: pick(WHEELS, 'aero-19', 'sport-20'),
    interiors: pick(INTERIORS, 'int-stone', 'int-tan', 'int-slate'),
    trims: TRIMS,
    accessories: pick(ACCESSORIES, 'acc-roof', 'acc-tow', 'acc-mats', 'acc-sound'),
    variants: [
      { id: 'phev', name: 'Estate Hybrid', price: 57800, power: 340, range: 980, acceleration: 5.6 },
      { id: 'phev-plus', name: 'Estate Hybrid Plus', price: 64900, power: 390, range: 940, acceleration: 5.0 },
    ],
    dimensions: { lengthMm: 4950, widthMm: 1900, heightMm: 1470, wheelbaseMm: 2920, cargoLiters: 640, weightKg: 2010 },
    features: ['Air suspension', 'Massage front seats', 'Electric tailgate', 'Rear sun blinds', 'Roof rails'],
    technology: ['90 km electric-only range', 'Predictive hybrid strategy', 'Head-up display', 'Matrix LED lighting'],
    safety: ['Adaptive cruise control', 'Exit warning', 'Rear collision mitigation', 'Eight airbags'],
    model3d: null,
    silhouette: 'wagon',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'wagon', profile: 'touring' },
  },
  {
    id: 'rivana-xr',
    slug: 'rivana-xr',
    manufacturer: 'Rivana',
    model: 'XR',
    variant: 'Adventure Pickup',
    year: 2026,
    tagline: 'Built for the places roads forget.',
    description:
      'A fully electric adventure pickup with quad-motor drive, a lockable gear tunnel and an onboard air compressor.',
    category: ['electric', 'adventure'],
    bodyType: 'pickup',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 835,
    torque: 1120,
    topSpeed: 180,
    acceleration: 3.3,
    range: 520,
    mileage: null,
    seats: 5,
    price: 79900,
    currency: 'USD',
    rating: 4.7,
    isNew: true,
    colors: [PALETTE.ember, PALETTE.sage, PALETTE.midnight, PALETTE.silver],
    wheels: pick(WHEELS, 'sport-20', 'forged-21'),
    interiors: pick(INTERIORS, 'int-stone', 'int-black'),
    trims: pick(TRIMS, 'trim-ash', 'trim-alu'),
    accessories: pick(ACCESSORIES, 'acc-tow', 'acc-roof', 'acc-mats', 'acc-charger'),
    variants: [
      { id: 'dual', name: 'Dual Motor', price: 69900, power: 600, range: 560, acceleration: 4.5 },
      { id: 'quad', name: 'Quad Motor', price: 79900, power: 835, range: 520, acceleration: 3.3 },
    ],
    dimensions: { lengthMm: 5510, widthMm: 2080, heightMm: 1820, wheelbaseMm: 3450, cargoLiters: 1600, weightKg: 3100 },
    features: ['Gear tunnel storage', 'Onboard air compressor', 'Camp mode', 'Powered tonneau cover', 'Underbody protection'],
    technology: ['Quad-motor torque vectoring', 'Adjustable ride height', 'Trailer assist', 'Off-road drive modes'],
    safety: ['Hill descent control', 'Camera-based towing view', 'Emergency braking', 'Eight airbags'],
    model3d: null,
    silhouette: 'pickup',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'pickup', profile: 'adventure' },
  },
  {
    id: 'solace-ev',
    slug: 'solace-ev',
    manufacturer: 'Solace',
    model: 'EV',
    variant: 'City Crossover',
    year: 2025,
    tagline: 'Calm energy for everyday life.',
    description:
      'Solace EV is an approachable compact electric crossover with a friendly design, lounge-like seating and a very competitive price.',
    category: ['electric', 'compact', 'family'],
    bodyType: 'crossover',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 204,
    torque: 310,
    topSpeed: 160,
    acceleration: 7.3,
    range: 430,
    mileage: null,
    seats: 5,
    price: 34500,
    currency: 'USD',
    rating: 4.6,
    isFeatured: true,
    colors: [PALETTE.pearl, PALETTE.glacier, PALETTE.ivory, PALETTE.indigo],
    wheels: pick(WHEELS, 'classic-18', 'aero-19'),
    interiors: pick(INTERIORS, 'int-stone', 'int-black'),
    trims: pick(TRIMS, 'trim-ash'),
    accessories: pick(ACCESSORIES, 'acc-charger', 'acc-mats', 'acc-roof'),
    variants: [
      { id: 'std', name: 'Standard', price: 34500, power: 204, range: 430, acceleration: 7.3 },
      { id: 'ext', name: 'Extended', price: 39900, power: 204, range: 510, acceleration: 7.5 },
    ],
    dimensions: { lengthMm: 4380, widthMm: 1830, heightMm: 1580, wheelbaseMm: 2760, cargoLiters: 470, weightKg: 1780 },
    features: ['Lounge front seats', 'Flat floor', 'Heat pump', 'Sliding centre console'],
    technology: ['Plug & charge', 'Smartphone digital key', 'Efficient heat pump climate', '12" central display'],
    safety: ['Pedestrian detection', 'Lane centring', 'Driver attention monitor', 'Seven airbags'],
    model3d: null,
    silhouette: 'hatch',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'hatch', profile: 'city-crossover' },
  },
  {
    id: 'ventra-rs',
    slug: 'ventra-rs',
    manufacturer: 'Ventra',
    model: 'RS',
    variant: 'Track Roadster',
    year: 2026,
    tagline: 'Nothing between you and the road.',
    description:
      'A lightweight electric roadster with a torque-rich rear motor and a manual-feel drive mode. The Ventra RS is pure driving distilled.',
    category: ['performance', 'electric'],
    bodyType: 'roadster',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 480,
    torque: 620,
    topSpeed: 265,
    acceleration: 2.9,
    range: 410,
    mileage: null,
    seats: 2,
    price: 96000,
    currency: 'USD',
    rating: 4.8,
    isNew: true,
    colors: [PALETTE.ember, PALETTE.glacier, PALETTE.midnight, PALETTE.pearl],
    wheels: pick(WHEELS, 'sport-20', 'forged-21'),
    interiors: pick(INTERIORS, 'int-black', 'int-slate'),
    trims: pick(TRIMS, 'trim-carbon', 'trim-alu'),
    accessories: pick(ACCESSORIES, 'acc-sound', 'acc-charger'),
    variants: [
      { id: 'rs', name: 'RS', price: 96000, power: 480, range: 410, acceleration: 2.9 },
      { id: 'rs-track', name: 'RS Track', price: 118000, power: 540, range: 380, acceleration: 2.6 },
    ],
    dimensions: { lengthMm: 4210, widthMm: 1880, heightMm: 1210, wheelbaseMm: 2500, cargoLiters: 160, weightKg: 1490 },
    features: ['Retractable soft top', 'Carbon bucket seats', 'Track mode', 'Simulated gear shifts'],
    technology: ['Rear-motor torque vectoring', 'Adaptive dampers', 'Lap timer', 'Lightweight battery pack'],
    safety: ['Roll-over protection', 'Stability control', 'Emergency braking', 'Four airbags'],
    model3d: null,
    silhouette: 'roadster',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'roadster', profile: 'track' },
  },
  {
    id: 'aureon-v9',
    slug: 'aureon-v9',
    manufacturer: 'Aureon',
    model: 'V9',
    variant: 'Executive Sedan',
    year: 2024,
    tagline: 'First-class, four doors.',
    description:
      'The flagship Aureon V9 focuses on rear-seat comfort with reclining seats, active noise cancellation and a whisper-quiet drivetrain.',
    category: ['luxury', 'electric'],
    bodyType: 'sedan',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 620,
    torque: 900,
    topSpeed: 240,
    acceleration: 3.8,
    range: 680,
    mileage: null,
    seats: 4,
    price: 124000,
    currency: 'USD',
    rating: 4.9,
    colors: [PALETTE.midnight, PALETTE.silver, PALETTE.indigo, PALETTE.ivory],
    wheels: pick(WHEELS, 'aero-19', 'forged-21'),
    interiors: pick(INTERIORS, 'int-tan', 'int-black', 'int-slate'),
    trims: TRIMS,
    accessories: pick(ACCESSORIES, 'acc-sound', 'acc-charger'),
    variants: [
      { id: 'exec', name: 'Executive', price: 124000, power: 620, range: 680, acceleration: 3.8 },
      { id: 'exec-l', name: 'Executive L', price: 139000, power: 620, range: 660, acceleration: 3.9 },
    ],
    dimensions: { lengthMm: 5240, widthMm: 1980, heightMm: 1480, wheelbaseMm: 3210, cargoLiters: 480, weightKg: 2450 },
    features: ['Reclining rear seats', 'Active noise cancellation', 'Rear climate zones', 'Soft-close doors'],
    technology: ['Silicon-carbide inverters', 'Rear-seat displays', 'Level-2+ highway assist', 'Digital light projection'],
    safety: ['Pre-collision system', 'Evasive steering', 'Night vision assist', 'Twelve airbags'],
    model3d: null,
    silhouette: 'sedan',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'sedan', profile: 'flagship' },
  },
  {
    id: 'kairo-cross',
    slug: 'kairo-cross',
    manufacturer: 'Kairo',
    model: 'Cross',
    variant: 'Adventure Compact',
    year: 2024,
    tagline: 'Weekend-ready, weekday-friendly.',
    description: 'The lifted Kairo Cross adds all-wheel drive, roof rails and rugged trim to the compact Kairo platform.',
    category: ['compact', 'adventure'],
    bodyType: 'crossover',
    fuelType: 'petrol',
    transmission: 'manual',
    power: 180,
    torque: 280,
    topSpeed: 200,
    acceleration: 7.8,
    range: 690,
    mileage: 15.6,
    seats: 5,
    price: 31200,
    currency: 'USD',
    rating: 4.4,
    colors: [PALETTE.sage, PALETTE.ember, PALETTE.graphite, PALETTE.pearl],
    wheels: pick(WHEELS, 'classic-18', 'aero-19'),
    interiors: pick(INTERIORS, 'int-stone', 'int-black'),
    trims: pick(TRIMS, 'trim-alu'),
    accessories: pick(ACCESSORIES, 'acc-roof', 'acc-tow', 'acc-mats'),
    variants: [
      { id: 'cross', name: 'Cross', price: 31200, power: 180, range: 690, acceleration: 7.8 },
      { id: 'cross-x', name: 'Cross X', price: 34800, power: 200, range: 660, acceleration: 7.2 },
    ],
    dimensions: { lengthMm: 4320, widthMm: 1810, heightMm: 1610, wheelbaseMm: 2650, cargoLiters: 430, weightKg: 1490 },
    features: ['Raised ride height', 'Roof rails', 'Rugged cladding', 'Hill descent control'],
    technology: ['Torque-on-demand AWD', 'Digital cockpit', 'Wireless smartphone integration', 'Rear camera'],
    safety: ['Emergency braking', 'Blind-spot monitoring', 'Lane departure warning', 'Six airbags'],
    model3d: null,
    silhouette: 'suv',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'suv', profile: 'compact-adventure' },
  },
  {
    id: 'velora-estate',
    slug: 'velora-estate',
    manufacturer: 'Velora',
    model: 'Estate',
    variant: 'Sport Wagon',
    year: 2025,
    tagline: 'Performance, with room to spare.',
    description:
      'The Velora Estate brings the GT drivetrain into a practical body: a rear-biased hybrid system, adaptive chassis and a huge boot.',
    category: ['performance', 'family', 'luxury'],
    bodyType: 'wagon',
    fuelType: 'hybrid',
    transmission: 'dual-clutch',
    power: 510,
    torque: 700,
    topSpeed: 280,
    acceleration: 3.9,
    range: 860,
    mileage: 13.4,
    seats: 5,
    price: 92000,
    currency: 'USD',
    rating: 4.7,
    colors: [PALETTE.crimson, PALETTE.graphite, PALETTE.pearl, PALETTE.midnight],
    wheels: pick(WHEELS, 'sport-20', 'forged-21'),
    interiors: pick(INTERIORS, 'int-black', 'int-tan', 'int-slate'),
    trims: pick(TRIMS, 'trim-carbon', 'trim-ash'),
    accessories: pick(ACCESSORIES, 'acc-roof', 'acc-sound', 'acc-mats'),
    variants: [
      { id: 'sport', name: 'Sport', price: 92000, power: 510, range: 860, acceleration: 3.9 },
      { id: 'sport-plus', name: 'Sport Plus', price: 104000, power: 560, range: 830, acceleration: 3.6 },
    ],
    dimensions: { lengthMm: 4930, widthMm: 1930, heightMm: 1440, wheelbaseMm: 2900, cargoLiters: 620, weightKg: 2090 },
    features: ['Sport seats', 'Adaptive chassis', 'Panoramic roof', 'Electric tailgate'],
    technology: ['Rear-biased hybrid AWD', 'Active exhaust', 'Head-up display', 'Predictive damping'],
    safety: ['Adaptive cruise control', 'Emergency braking', 'Cross-traffic alert', 'Eight airbags'],
    model3d: null,
    silhouette: 'wagon',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'wagon', profile: 'sport-estate' },
  },
  {
    id: 'nexen-city',
    slug: 'nexen-city',
    manufacturer: 'Nexen',
    model: 'City',
    variant: 'Micro EV',
    year: 2026,
    tagline: 'The smart way through town.',
    description:
      'A two-plus-two micro electric car with a tiny footprint, swappable interior panels and enough range for a week of commuting.',
    category: ['electric', 'compact'],
    bodyType: 'hatchback',
    fuelType: 'electric',
    transmission: 'single-speed',
    power: 95,
    torque: 180,
    topSpeed: 130,
    acceleration: 10.8,
    range: 280,
    mileage: null,
    seats: 4,
    price: 19900,
    currency: 'USD',
    rating: 4.3,
    isNew: true,
    colors: [PALETTE.glacier, PALETTE.ember, PALETTE.ivory, PALETTE.cobalt],
    wheels: pick(WHEELS, 'classic-18'),
    interiors: pick(INTERIORS, 'int-stone'),
    trims: pick(TRIMS, 'trim-ash'),
    accessories: pick(ACCESSORIES, 'acc-charger', 'acc-mats'),
    variants: [{ id: 'city', name: 'City', price: 19900, power: 95, range: 280, acceleration: 10.8 }],
    dimensions: { lengthMm: 3620, widthMm: 1680, heightMm: 1540, wheelbaseMm: 2420, cargoLiters: 260, weightKg: 1120 },
    features: ['Swappable interior panels', 'Fold-flat rear seats', 'Compact turning circle', 'Removable speaker'],
    technology: ['Fast AC charging', 'Companion app', '8" display', 'Smartphone key'],
    safety: ['Emergency braking', 'Lane keep assist', 'Rear parking sensors', 'Six airbags'],
    model3d: null,
    silhouette: 'hatch',
    renderMode: 'procedural',
    renderConfig: { silhouette: 'hatch', profile: 'micro-ev' },
  },
];
